name = "shared-env-r2-persist"
main = "dist/index.mjs"
compatibility_date = "2022-05-28"
compatibility_flags = []

[[r2_buckets]]
binding = 'LANGUAGE_FILES'
bucket_name = '<ignored>'

[build]
command = "node build.js"

[miniflare]
kv_persist = true
cache_persist = true
r2_persist = true

